---
- name: Download repository
  tags: downloaded
  file:
    path: /opt/prometheus
    state: directory

- name: Prometheus download from a source
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz
    dest: /opt/prometheus
    remote_src: yes
    mode: 0777
    owner: root
    group: root

- name: Prometheus repository
  shell: |
    cd /opt/prometheus/prometheus*
    cp -r . /usr/local/bin/prometheus

- name: Prometheus Service File
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
    mode: 0644
    owner: root
    group: root

- name: Prometheus Stop
  service:
    name: prometheus
    state: stopped

- name: Prometheus Restart
  service:
    name: prometheus
    state: restarted
    enabled: yes

